name: Branch Protection 
 
on:
  branch_protection_rule:
    types: [created, deleted]
 
jobs:
  bp-rules:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log event details
        run: echo " Branch Protection Rules Triggered this"
