name: Permissions Example

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Repository Files
        run: ls -la
