name: Workflow1

on:
  workflow_call:
    inputs:
      message:
        description: "A custom message for the workflow"
        required: true
        type: string
    

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Custom Message
        run: echo "Message: ${{ inputs.message }}"
